# Generated by Django 4.0.5 on 2022-07-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='url',
        ),
        migrations.AddField(
            model_name='photo',
            name='picture',
            field=models.FileField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postcreated',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
