# Generated by Django 4.0.5 on 2022-07-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static/img/default_photo.jpeg', upload_to='profile_pics'),
        ),
    ]
