# Generated by Django 4.0.4 on 2022-07-04 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_savedpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedpost',
            name='description',
        ),
        migrations.RemoveField(
            model_name='savedpost',
            name='image',
        ),
        migrations.RemoveField(
            model_name='savedpost',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='savedpost',
            name='title',
        ),
        migrations.AddField(
            model_name='savedpost',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.postcreated'),
            preserve_default=False,
        ),
    ]
