# Generated by Django 4.0.5 on 2022-06-24 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_post_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Postc',
        ),
    ]
