# Generated by Django 4.0.5 on 2022-06-24 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_post_postc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postc',
            new_name='Postcreated',
        ),
    ]
