# Generated by Django 4.0.5 on 2022-06-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_photo_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcreated',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
