# Generated by Django 4.0.5 on 2022-06-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_description_profile_bio_profile_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.URLField(),
        ),
    ]
