# Generated by Django 4.0.5 on 2022-06-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_postcreated_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='url',
        ),
        migrations.AlterField(
            model_name='postcreated',
            name='image',
            field=models.FileField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
