# Generated by Django 4.0.5 on 2022-06-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_photo_url_alter_postcreated_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcreated',
            name='user',
        ),
        migrations.AlterField(
            model_name='postcreated',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
