# Generated by Django 4.0.5 on 2022-06-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_postcreated_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcreated',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
